//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHAHANGWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.BaiViets = new HashSet<BaiViet>();
            this.HopThus = new HashSet<HopThu>();
        }
    
        public int NguoiDungID { get; set; }
        public string TenDangNhap { get; set; }
        public string Matkhau { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<BaiViet> BaiViets { get; set; }
        public virtual ICollection<HopThu> HopThus { get; set; }
    }
}
