//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHAHANGWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanLoai
    {
        public PhanLoai()
        {
            this.NhomMons = new HashSet<NhomMon>();
        }
    
        public int PhanLoaiID { get; set; }
        public string TenPhanLoai { get; set; }
        public string BiDanh { get; set; }
    
        public virtual ICollection<NhomMon> NhomMons { get; set; }
    }
}
