//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHAHANGWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucDon
    {
        public ThucDon()
        {
            this.DatHangCTs = new HashSet<DatHangCT>();
        }
    
        public int ThucDonID { get; set; }
        public string TenThucDon { get; set; }
        public int DonGia { get; set; }
        public int KhuyenMai { get; set; }
        public string MoTa { get; set; }
        public string Hinh { get; set; }
        public short ThuocMien { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public int NhomMonID { get; set; }
        public bool NgungBan { get; set; }
        public string BiDanh { get; set; }
    
        public virtual ICollection<DatHangCT> DatHangCTs { get; set; }
        public virtual NhomMon NhomMon { get; set; }
    }
}
